@baseUrl = http://localhost:8080

### Transactions

GET {{baseUrl}}/transactions

### Address

GET {{baseUrl}}/address

### Check address

GET {{baseUrl}}/address/EQAWjHh5HshDy1FJmdS40siWXtzQGL4fDfWbo-Y523KFsDdJ
